// packages/core/i18n/src/utils/config.ts

/**
 * @fileoverview i18n configuration utility
 * @description Utilities for accessing i18n configuration across platforms
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */

import type { I18nPluginConfig } from '@donotdev/types';
import { getDndevConfig } from '@donotdev/utils';

/**
 * Get i18n configuration from unified DnDev config
 * Works across Vite and Next.js platforms
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
export function getI18nConfig(): I18nPluginConfig {
  // Use DRY utility for platform-aware config access
  const config = getDndevConfig();
  if (config?.i18n) {
    return config.i18n;
  }

  // Next.js: Environment variable fallback
  if (typeof process !== 'undefined' && process.env._DNDEV_CONFIG_) {
    try {
      const config = JSON.parse(process.env._DNDEV_CONFIG_);
      if (config.i18n) return config.i18n;
    } catch (error) {
      console.warn(
        '[i18n] Failed to parse DnDev config from environment:',
        error
      );
    }
  }

  // Minimal fallback configuration
  return {
    mapping: {},
    languages: ['en'],
    eager: [],
    fallback: 'en',
    storage: {
      type: 'localStorage',
      prefix: 'dndev_i18n_',
      ttl: 24 * 60 * 60 * 1000,
      encryption: false,
      maxSize: 5 * 1024 * 1024,
    },
    performance: {
      cacheSize: 100,
      errorCacheTTL: 30000,
    },
    manifest: {
      totalFiles: 0,
      totalNamespaces: 0,
      totalLanguages: 1,
      eagerNamespaces: 0,
      generatedAt: new Date().toISOString(),
    },
    debug: false,
  };
}

/**
 * Merge user config with discovered config
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
/**
 * Merge user config with discovered config
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
export function mergeWithDefaults(
  userConfig?: Partial<I18nPluginConfig>
): I18nPluginConfig {
  const base = getI18nConfig();
  return { ...base, ...userConfig };
}

/**
 * Validate i18n configuration
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
/**
 * Validate i18n configuration
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
export function validateConfig(config: I18nPluginConfig): I18nPluginConfig {
  // Ensure required arrays exist
  if (!config.languages || config.languages.length === 0) {
    config.languages = ['en'];
  }

  if (!config.fallback || !config.languages.includes(config.fallback)) {
    config.fallback = config.languages[0] || 'en';
  }

  return config;
}

// Simple accessors for common config values
/**
 * Get virtual mapping configuration
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
export function getVirtualMapping() {
  return getI18nConfig().mapping;
}

/**
 * Get eager namespaces
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
export function getEagerNamespaces() {
  return getI18nConfig().eager;
}

/**
 * Get supported language codes
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
export function getSupportedLanguageCodes() {
  return getI18nConfig().languages;
}

/**
 * Get fallback language
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
export function getFallbackLanguage() {
  return getI18nConfig().fallback;
}

/**
 * Get translation content
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
export function getTranslationContent() {
  return getI18nConfig().content || {};
}

/**
 * Get lazy translation loader functions
 * These are static import() calls generated by the Vite plugin
 */
export function getTranslationLoaders(): Record<
  string,
  Record<string, () => Promise<any>>
> {
  return getI18nConfig().loaders || {};
}

/**
 * Get storage configuration
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
export function getStorageConfig() {
  return getI18nConfig().storage;
}

/**
 * Get performance configuration
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
export function getPerformanceConfig() {
  return getI18nConfig().performance;
}

/**
 * Check if debug mode is enabled
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */
export function isDebugEnabled() {
  return getI18nConfig().debug;
}
