/**
 * @fileoverview Copy @fontsource font files to public/ for Next.js
 * @description Turbopack can't resolve CSS url() from node_modules after inlining.
 * This copies woff2 files to public/fonts/ and generates public/dndev-fonts.css
 * with corrected absolute url() paths. Called during discovery phase.
 *
 * Two modes:
 * - Monorepo (src/dndev.css exists): parse @import '@fontsource/...' → resolve each package
 * - Consumer (only dist/dndev.css): parse inlined @font-face with url(./files/...) → copy from ui/dist/files/
 *
 * When `languages` is provided, only copies font files for needed subsets (locale-aware filtering).
 */

import { LOCALE_TO_FONT_SUBSETS, FONT_WEIGHTS } from '../../constants.js';
import { stripWoffFromSrc } from '../../fonts/resolveFontManifest.js';
import { createLogger } from '../../utils/debugLog.js';
import { PathResolver } from '../../utils/PathResolver.js';

const PUBLIC_FONTS_DIR = 'fonts';
const FONTS_CSS_FILENAME = 'dndev-fonts.css';

/** Regex to extract @fontsource imports from src/dndev.css */
const FONTSOURCE_IMPORT_RE =
  /@import\s+['"]@fontsource\/([^/]+)\/(\d+)\.css['"]/g;

/** Regex to extract url(./files/filename) from inlined CSS */
const URL_FILES_RE = /url\(\.\/files\/([^)]+)\)/g;

/**
 * Resolve needed subsets from locale list.
 * @param {string[]} languages
 * @returns {Set<string>}
 */
function resolveSubsets(languages) {
  const subsets = new Set(['latin']);
  for (const locale of languages) {
    const localeSubsets = LOCALE_TO_FONT_SUBSETS[locale];
    if (localeSubsets) {
      for (const s of localeSubsets) subsets.add(s);
    }
  }
  return subsets;
}

/**
 * Parse src/dndev.css to extract @fontsource [package, weight] pairs.
 * @param {Object} pathResolver
 * @param {string} uiPkg - resolved @donotdev/ui package root
 * @returns {Array<[string, string]>}
 */
function parseFontImports(pathResolver, uiPkg) {
  // Try src/dndev.css first (monorepo with workspace:*)
  const srcPath = pathResolver.resolvePath('src/dndev.css', uiPkg);
  const css = pathResolver.readSync(srcPath, { format: 'text' });
  if (!css) return [];

  const imports = [];
  let match;
  while ((match = FONTSOURCE_IMPORT_RE.exec(css)) !== null) {
    imports.push([match[1], match[2]]);
  }
  return imports;
}

/**
 * Monorepo path: resolve each @fontsource package, copy files, rewrite CSS.
 * When subsets is provided, reads subset-specific CSS files instead of all-subsets.
 */
function copyFromFontsource(
  pathResolver,
  fontImports,
  fontsDir,
  logger,
  subsets
) {
  const cssChunks = ['/* Auto-generated by @donotdev/core — do not edit */\n'];
  const copiedFiles = new Set();
  const filterBySubset = subsets && subsets.size > 0;

  for (const [pkg, weight] of fontImports) {
    const pkgRoot = pathResolver.resolveFrameworkPackage(`@fontsource/${pkg}`);
    if (!pkgRoot) {
      logger.debug(`@fontsource/${pkg} not found`);
      continue;
    }

    // Only filter known framework fonts — unknown/custom fonts pass through
    const isKnownFont = !!FONT_WEIGHTS[pkg];

    if (filterBySubset && isKnownFont) {
      // Read subset-specific CSS files (e.g. latin-400.css, cyrillic-400.css)
      for (const subset of subsets) {
        const subsetCssFile = pathResolver.resolvePath(
          `${subset}-${weight}.css`,
          pkgRoot
        );
        const css = pathResolver.readSync(subsetCssFile, { format: 'text' });
        if (!css) continue; // Subset doesn't exist for this font

        const rewritten = processCSS(
          stripWoffFromSrc(css),
          pathResolver,
          pkgRoot,
          fontsDir,
          copiedFiles,
          logger,
          true // woff2Only
        );
        cssChunks.push(rewritten);
      }
    } else {
      // Legacy: read all-subsets aggregated file
      const cssFile = pathResolver.resolvePath(`${weight}.css`, pkgRoot);
      const css = pathResolver.readSync(cssFile, { format: 'text' });
      if (!css) {
        logger.debug(`Missing: @fontsource/${pkg}/${weight}.css`);
        continue;
      }

      const rewritten = processCSS(
        css,
        pathResolver,
        pkgRoot,
        fontsDir,
        copiedFiles,
        logger,
        false
      );
      cssChunks.push(rewritten);
    }
  }

  return { cssChunks, copiedFiles };
}

/**
 * Process CSS: rewrite url() paths, copy font files.
 * @param {string} css - CSS content
 * @param {Object} pathResolver
 * @param {string} pkgRoot - @fontsource package root
 * @param {string} fontsDir - target public/fonts/ directory
 * @param {Set<string>} copiedFiles - tracker for already-copied files
 * @param {Object} logger
 * @param {boolean} woff2Only - skip .woff files
 * @returns {string} rewritten CSS
 */
function processCSS(
  css,
  pathResolver,
  pkgRoot,
  fontsDir,
  copiedFiles,
  logger,
  woff2Only
) {
  return css.replace(URL_FILES_RE, (_match, filename) => {
    // Skip .woff files when filtering
    if (woff2Only && filename.endsWith('.woff')) {
      return 'url(data:,)';
    }

    const src = pathResolver.resolvePath(`files/${filename}`, pkgRoot);
    const srcExists = pathResolver.pathExists(src);

    if (!srcExists) {
      logger.warn(`Font file missing: ${src} — dropping from CSS`);
      return 'url(data:,)';
    }

    if (!copiedFiles.has(filename)) {
      const dest = pathResolver.resolvePath(filename, fontsDir);
      pathResolver.copySync(src, dest, { overwrite: true });
      copiedFiles.add(filename);
    }

    return `url(/${PUBLIC_FONTS_DIR}/${filename})`;
  });
}

/** Regex to extract @font-face blocks from inlined CSS */
const FONT_FACE_BLOCK_RE = /@font-face\s*\{[^}]*\}/g;

/**
 * Consumer path: parse dist/dndev.css (inlined @font-face), copy from ui/dist/files/.
 * Only extracts @font-face blocks — everything else (variables, base styles) is excluded.
 * When subsets is provided, filters @font-face blocks to only include needed subsets.
 */
function copyFromDistCSS(pathResolver, uiPkg, fontsDir, logger, subsets) {
  const distCssPath = pathResolver.resolvePath('dist/dndev.css', uiPkg);
  const css = pathResolver.readSync(distCssPath, { format: 'text' });
  if (!css) {
    logger.debug('dist/dndev.css not found in @donotdev/ui');
    return { cssChunks: [], copiedFiles: new Set() };
  }

  // Extract only @font-face blocks from the full bundled CSS
  let fontFaceBlocks = css.match(FONT_FACE_BLOCK_RE);
  if (!fontFaceBlocks || fontFaceBlocks.length === 0) {
    logger.debug('No @font-face blocks found in dist/dndev.css');
    return { cssChunks: [], copiedFiles: new Set() };
  }

  const filterBySubset = subsets && subsets.size > 0;

  // Build set of known font stems for filtering
  const knownStems = new Set(Object.keys(FONT_WEIGHTS));

  // Filter blocks by subset if languages provided (only for known fonts)
  if (filterBySubset) {
    fontFaceBlocks = fontFaceBlocks.filter((block) => {
      // Check if this block is for a known font
      const isKnown = Array.from(knownStems).some((stem) =>
        block.includes(`${stem}-`)
      );
      // Unknown fonts → keep (passthrough)
      if (!isKnown) return true;
      // Known fonts → keep only if matches a needed subset
      for (const subset of subsets) {
        if (block.includes(`-${subset}-`)) return true;
      }
      return false;
    });
  }

  const distFilesDir = pathResolver.resolvePath('dist/files', uiPkg);
  const copiedFiles = new Set();

  const rewrittenBlocks = fontFaceBlocks.map((block) => {
    // Only strip woff for known fonts
    const isKnown =
      filterBySubset &&
      Array.from(knownStems).some((stem) => block.includes(`${stem}-`));
    let processed = isKnown ? stripWoffFromSrc(block) : block;
    return processed.replace(URL_FILES_RE, (_match, filename) => {
      // Skip .woff files for known fonts (already stripped by stripWoffFromSrc,
      // but guard in case url() survived in a format we didn't match)
      if (isKnown && filename.endsWith('.woff')) {
        return 'url(data:,)';
      }

      const src = pathResolver.resolvePath(filename, distFilesDir);
      const srcExists = pathResolver.pathExists(src);

      if (!srcExists) {
        logger.warn(`Font file missing: ${src} — dropping from CSS`);
        return 'url(data:,)';
      }

      if (!copiedFiles.has(filename)) {
        const dest = pathResolver.resolvePath(filename, fontsDir);
        pathResolver.copySync(src, dest, { overwrite: true });
        copiedFiles.add(filename);
      }

      return `url(/${PUBLIC_FONTS_DIR}/${filename})`;
    });
  });

  const cssChunks = [
    '/* Auto-generated by @donotdev/core — do not edit */\n',
    ...rewrittenBlocks,
  ];

  return { cssChunks, copiedFiles };
}

/**
 * Copy font files to public/fonts/ and generate public/dndev-fonts.css.
 *
 * @param {Object} [options]
 * @param {boolean} [options.debug] - Enable debug logging
 * @param {boolean} [options.force] - Force regeneration even if files exist
 * @param {string[]} [options.languages] - App locales for subset filtering (e.g. ['en', 'fr'])
 */
export function copyFontsToPublic({
  debug = false,
  force = false,
  languages,
} = {}) {
  const logger = createLogger('font-copy', debug, false);
  const pathResolver = PathResolver.getInstance();

  const fontsCssPath = pathResolver.resolveAppPath(
    `public/${FONTS_CSS_FILENAME}`
  );

  // Skip if already generated (unless forced)
  if (!force && pathResolver.pathExists(fontsCssPath)) {
    logger.debug('dndev-fonts.css already exists, skipping font copy');
    return;
  }

  const uiPkg = pathResolver.resolveFrameworkPackage('@donotdev/ui');
  if (!uiPkg) {
    logger.debug('@donotdev/ui not found, skipping font copy');
    return;
  }

  // Ensure public/fonts/ exists
  const fontsDir = pathResolver.resolveAppPath(`public/${PUBLIC_FONTS_DIR}`);
  pathResolver.ensureDir(fontsDir);

  // Resolve needed subsets from languages
  const subsets = languages?.length ? resolveSubsets(languages) : null;

  if (subsets) {
    logger.debug(
      `Font copy: locale-aware filtering — locales=[${languages.join(',')}] subsets=[${[...subsets].join(',')}]`
    );
  }

  // Try monorepo path first (src/dndev.css with @import '@fontsource/...')
  const fontImports = parseFontImports(pathResolver, uiPkg);

  let cssChunks;
  let copiedFiles;

  if (fontImports.length > 0) {
    // Monorepo: resolve @fontsource packages individually
    logger.debug(
      `Monorepo mode: ${fontImports.length} @fontsource imports found`
    );
    ({ cssChunks, copiedFiles } = copyFromFontsource(
      pathResolver,
      fontImports,
      fontsDir,
      logger,
      subsets
    ));
  } else {
    // Consumer: parse inlined @font-face from dist/dndev.css
    logger.debug('Consumer mode: parsing dist/dndev.css for font files');
    ({ cssChunks, copiedFiles } = copyFromDistCSS(
      pathResolver,
      uiPkg,
      fontsDir,
      logger,
      subsets
    ));
  }

  if (copiedFiles.size === 0) {
    logger.debug('No font files found to copy');
    return;
  }

  // Write concatenated CSS with corrected paths
  pathResolver.writeSync(fontsCssPath, cssChunks.join('\n'));
  logger.debug(
    `Font copy: wrote ${FONTS_CSS_FILENAME} (${copiedFiles.size} font files copied)`
  );
}

/**
 * Clean up generated font files from public/.
 */
export function cleanFontAssets() {
  const pathResolver = PathResolver.getInstance();
  const fontsCssPath = pathResolver.resolveAppPath(
    `public/${FONTS_CSS_FILENAME}`
  );
  const fontsDir = pathResolver.resolveAppPath(`public/${PUBLIC_FONTS_DIR}`);

  if (pathResolver.pathExists(fontsCssPath)) {
    try {
      pathResolver.removeSync(fontsCssPath);
    } catch {
      /* ignore */
    }
  }

  if (pathResolver.pathExists(fontsDir)) {
    try {
      pathResolver.removeSync(fontsDir);
    } catch {
      /* ignore */
    }
  }
}
