// packages/core/schemas/src/common/visibility.ts

/**
 * @fileoverview The 4 Field Families
 * @description Every entity in the framework is composed of 4 families
 *
 * ## The 4 Families
 *
 * ```
 * Entity = Technical Fields + Status Field + User Fields (Framework Types or Custom Types)
 * ```
 *
 * ### Family 1: TECHNICAL_FIELDS (Backend-Generated)
 * **Members**: `id`, `createdAt`, `updatedAt`, `createdById`, `updatedById`
 *
 * **Rules**:
 * - ✓ Always present (framework adds automatically)
 * - ✗ Users cannot set (stripped from submissions)
 * - ✓ Read-only in edit forms
 * - ✓ Auto-generated by server
 *
 * ### Family 2: STATUS_FIELD (Lifecycle Management)
 * **Member**: `status`
 *
 * **Default Values**: `'draft'`, `'available'`, `'deleted'`
 *
 * **Rules**:
 * - ✓ Always present (framework adds)
 * - ✓ Users must set value
 * - ✓ Users can add custom values (`'reserved'`, `'sold'`)
 * - ✗ Cannot remove default values
 * - ✓ Draft mode (`status === 'draft'`) relaxes validation
 *
 * ### Family 3: FRAMEWORK_TYPES (~30 Built-in)
 * **Available Types**:
 * - Text: `text`, `textarea`, `email`, `tel`, `url`, `password`
 * - Numbers: `number`, `range`
 * - Dates: `date`, `datetime-local`, `time`, `timestamp`
 * - Choices: `select`, `multiselect`, `radio`, `checkbox`, `combobox`, `switch`
 * - Media: `image`, `images`, `file`
 * - Special: `reference`, `geopoint`, `address`, `map`
 *
 * ### Family 4: CUSTOM_TYPES (User-Registered)
 * **What**: Custom field types registered via `registerFieldType()`
 *
 * **Examples**: `repairOperations`, `ratp`, custom widgets
 *
 * ## Complete Example
 *
 * ```typescript
 * import { defineEntity } from '@donotdev/core';
 * import { registerFieldType } from '@donotdev/crud';
 *
 * // Register custom type (Family 4)
 * registerFieldType('repairOperations', {
 *   schema: (field) => v.array(v.object({ operation: v.string(), cost: v.number() })),
 *   component: RepairOperationsField
 * });
 *
 * // Define entity
 * const carEntity = defineEntity({
 *   name: 'Car',
 *   collection: 'cars',
 *   fields: {
 *     // User fields using FRAMEWORK_TYPES (Family 3)
 *     make: { type: 'text', validation: { required: true } },
 *     year: { type: 'number' },
 *     images: { type: 'images' },
 *     fuelType: { type: 'select', validation: { options: [...] } },
 *
 *     // User field using CUSTOM_TYPES (Family 4)
 *     repairs: { type: 'repairOperations', visibility: 'admin' },
 *
 *     // Extend STATUS_FIELD (Family 2)
 *     status: {
 *       validation: {
 *         options: [
 *           { value: 'reserved', label: 'Reserved' },
 *           { value: 'sold', label: 'Sold' }
 *         ]
 *       }
 *     }
 *
 *     // TECHNICAL_FIELDS (Family 1) auto-added by framework
 *   }
 * });
 * ```
 *
 * **Result**:
 * - Family 1 (Technical): `id`, `createdAt`, `updatedAt`, `createdById`, `updatedById`
 * - Family 2 (Status): `status` with `draft/available/deleted/reserved/sold`
 * - User fields: `make`, `year`, `images`, `fuelType`, `repairs`
 *
 * @version 0.1.0
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */

import {
  type EntityField,
  type FieldType,
  type Visibility,
} from '@donotdev/types';

// Visibility logic moved to @donotdev/utils
// Import from: import { isFieldVisible, getVisibleFields } from '@donotdev/utils';
// Or for server: import { isFieldVisible, getVisibleFields } from '@donotdev/utils/server';
//
// Uses hasRoleAccess() for hierarchical visibility check:
// - guest < user < admin < super
// - technical: admins+ only
// - hidden: never exposed

/**
 * Type-safe base fields that all entities inherit
 * Each field has its specific type for proper TypeScript inference
 */
export interface TypedBaseFields {
  id: EntityField<'text'>;
  createdAt: EntityField<'timestamp'>;
  updatedAt: EntityField<'timestamp'>;
  createdById: EntityField<'reference'>;
  updatedById: EntityField<'reference'>;
  status: EntityField<'select'>;
}

/**
 * Default status options for draft/publish/delete workflow
 * Framework provides 'draft', 'available', 'deleted' - consumers can extend
 *
 * Translation fallback order: entity-{name} → crud (never dndev)
 * - Framework defaults: crud:status.draft, crud:status.available, crud:status.deleted
 * - User overrides: entity-{name}_*.json files (e.g., entity-inquiry_en.json: "status.draft": "New")
 *
 * CRUD is optional and shouldn't pollute core framework (dndev) namespace
 */
export const DEFAULT_STATUS_OPTIONS = [
  { value: 'draft', label: 'crud:status.draft' },
  { value: 'available', label: 'crud:status.available' },
  { value: 'deleted', label: 'crud:status.deleted' },
] as const;

/**
 * Default status value for new documents (visible immediately).
 * Forms use 'draft' explicitly for save-and-finish-later flows.
 */
export const DEFAULT_STATUS_VALUE = 'available' as const;

/**
 * Statuses that are hidden from non-admin users
 */
export const HIDDEN_STATUSES = ['draft', 'deleted'] as const;

/**
 * Fields that are TRULY backend-generated (cannot be set by user)
 * These are stripped from create operations - backend creates them automatically
 *
 * @category Field Families
 * @constant BACKEND_GENERATED_FIELD_NAMES
 */
export const BACKEND_GENERATED_FIELD_NAMES = [
  'id', // Firestore auto-generates document ID
  'createdAt', // Server sets creation timestamp
  'updatedAt', // Server sets update timestamp
  'createdById', // Server extracts from auth context
  'updatedById', // Server extracts from auth context
] as const;

/**
 * List of technical field names that are auto-generated by the backend
 * Includes backend-generated fields + status field
 *
 * These fields are optional in create schemas (backend creates them automatically).
 * They can be updated in update operations if provided.
 *
 * **Note**: Status is included here for visibility/editability logic but is NOT stripped
 * from form submissions since users MUST set it. Use BACKEND_GENERATED_FIELD_NAMES for stripping.
 *
 * @category Field Families
 * @constant TECHNICAL_FIELD_NAMES
 */
export const TECHNICAL_FIELD_NAMES = [
  ...BACKEND_GENERATED_FIELD_NAMES,
  'status', // Framework-enforced, user-settable (NOT backend-generated)
] as const;

/**
 * TypeScript Helper Types for Field Families
 * @category Field Families
 */

/** Type for backend-generated field names */
export type BackendGeneratedField =
  (typeof BACKEND_GENERATED_FIELD_NAMES)[number];

/** Type for the status field */
export type StatusField = 'status';

/** Type for all technical field names */
export type TechnicalField = (typeof TECHNICAL_FIELD_NAMES)[number];

/**
 * Type guard to check if a field name is a framework-managed field
 * @param fieldName - Field name to check
 * @returns True if field is in TECHNICAL_FIELD_NAMES
 *
 * @example
 * ```typescript
 * if (isFrameworkField('status')) {
 *   // Field is framework-managed (cannot remove)
 * }
 * ```
 */
export function isFrameworkField(
  fieldName: string
): fieldName is TechnicalField {
  return TECHNICAL_FIELD_NAMES.includes(fieldName as TechnicalField);
}

/**
 * Type guard to check if a field is backend-generated
 * @param fieldName - Field name to check
 * @returns True if field is auto-generated by backend
 *
 * @example
 * ```typescript
 * if (isBackendGeneratedField('createdAt')) {
 *   // Field is backend-generated (should be stripped on create)
 * }
 * ```
 */
export function isBackendGeneratedField(
  fieldName: string
): fieldName is BackendGeneratedField {
  return BACKEND_GENERATED_FIELD_NAMES.includes(
    fieldName as BackendGeneratedField
  );
}

// Re-export the base technical fields with proper generic types
// Note: name and label will be added by defineEntity, but we include them here for type consistency
export const baseFields: TypedBaseFields = {
  status: {
    name: 'status',
    type: 'select',
    visibility: 'admin',
    label: 'crud:fields.status',
    editable: 'admin', // REQUIRED: Status must be editable to be included in forms
    validation: {
      required: true,
      options: [...DEFAULT_STATUS_OPTIONS],
    },
  },
  id: {
    name: 'id',
    type: 'text',
    visibility: 'hidden',
    label: 'crud:fields.id',
    validation: {
      required: true,
    },
  },
  createdAt: {
    name: 'createdAt',
    type: 'timestamp',
    visibility: 'technical',
    label: 'crud:fields.createdAt',
    validation: {},
  },
  updatedAt: {
    name: 'updatedAt',
    type: 'timestamp',
    visibility: 'technical',
    label: 'crud:fields.updatedAt',
    validation: {},
  },
  createdById: {
    name: 'createdById',
    type: 'reference',
    visibility: 'technical',
    label: 'crud:fields.createdById',
    validation: {},
  },
  updatedById: {
    name: 'updatedById',
    type: 'reference',
    visibility: 'technical',
    label: 'crud:fields.updatedById',
    validation: {},
  },
};
