/**
 * @fileoverview Next.js Blog Content Handler
 * @description Scans `src/content/blog/*.md` files and generates
 * `src/content/blog/blog-content.generated.ts` — the file that
 * the `virtual:donotdev/blog` webpack alias points to.
 *
 * @version 0.0.1
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */

import fs from 'node:fs';
import path from 'node:path';
import { BaseNextHandler } from './BaseNextHandler.js';
import { GENERATED_PATHS } from '../../constants.js';

// ===== INLINE DISCOVERY =====

class BlogContentDiscovery {
  /**
   * @param {import('../../utils/PathResolver.js').PathResolver} pathResolver
   */
  constructor(pathResolver) {
    this.pathResolver = pathResolver;
  }

  /**
   * Return relative paths (`./slug_lang.md`) of all `.md` files in
   * `src/content/blog/` relative to that directory, plus the absolute
   * path to the blog directory.
   *
   * @returns {{ blogDir: string, files: string[] }}
   */
  discoverBlogFiles() {
    const blogDir = this.pathResolver.resolveAppPath('src/content/blog');

    if (!fs.existsSync(blogDir)) {
      return { blogDir, files: [] };
    }

    let entries;
    try {
      entries = fs.readdirSync(blogDir);
    } catch {
      return { blogDir, files: [] };
    }

    const files = entries
      .filter((f) => f.endsWith('.md') && !f.startsWith('.'))
      .sort();

    return { blogDir, files };
  }
}

// ===== HANDLER =====

export class NextBlogContentHandler extends BaseNextHandler {
  constructor(options = {}) {
    super(BlogContentDiscovery, options);
  }

  // === HANDLER CONFIGURATION ===

  getHandlerDefaults() {
    return {
      outputPath: GENERATED_PATHS.next.blogContent,
    };
  }

  getHandlerName() {
    return 'BlogContent';
  }

  createDiscovery(discoveryClass) {
    return new discoveryClass(this.pathResolver);
  }

  // === OVERRIDE generateFiles() ===
  // Blog handler only generates the `.ts` content file — it has no
  // dndev-config-*.js, no manifest, no API handler.

  async generateFiles() {
    try {
      const data = await this.getDiscoveryData();

      if (this.options.verbose) {
        this.logDiscoveryResults(data);
      }

      await this.generateSpecificFiles(data);

      this.logger.debug(
        `Generated BlogContent: ${this.getGenerationSummary(data)}`
      );

      return data;
    } catch (error) {
      this.logger.debug(
        `BlogContent generation failed (non-critical): ${error.message}`
      );
      // Non-critical — don't rethrow
      return { blogDir: '', files: [] };
    }
  }

  // === DISCOVERY ===

  async getDiscoveryData() {
    return this.discovery.discoverBlogFiles();
  }

  logDiscoveryResults(data) {
    this.logger.info(`📝 Blog: ${data.files.length} .md file(s) found`);
  }

  getGenerationSummary(data) {
    return `${data.files.length} blog file(s)`;
  }

  // === FILE GENERATION ===

  async generateSpecificFiles(data) {
    const { blogDir, files } = data;

    if (files.length === 0) {
      this.logger.debug(
        'No .md files in src/content/blog/ — skipping blog-content.generated.ts'
      );
      return;
    }

    const content = this._buildGeneratedContent(blogDir, files);
    this.writeGeneratedFile(this.options.outputPath, content, 'blog content manifest');
  }

  /**
   * Build the generated TS module that maps `./slug_lang.md` → raw markdown.
   *
   * Markdown is inlined as JS string literals (via JSON.stringify) instead of
   * `import './foo.md'`. This keeps the module bundler-agnostic — Turbopack
   * (Next.js 16) has no built-in `.md` loader and webpack rules don't apply to
   * Turbopack, so static `.md` imports break `next dev` / `next build`.
   * Inlining sidesteps the loader question entirely.
   *
   * @param {string} blogDir - Absolute path to the blog directory
   * @param {string[]} files - Markdown filenames (e.g. `slug_en.md`)
   * @returns {string} TypeScript source for the generated manifest
   */
  _buildGeneratedContent(blogDir, files) {
    const entries = files
      .map((f) => {
        const raw = fs.readFileSync(path.join(blogDir, f), 'utf8');
        return `  './${f}': ${JSON.stringify(raw)},`;
      })
      .join('\n');

    return `// Generated by @donotdev/config - DO NOT EDIT
// Regenerated when src/content/blog/*.md files change

const blogContent: Record<string, string> = {
${entries}
};

export default blogContent;
`;
  }

  // === UNUSED ABSTRACT STUBS (not needed for blog handler) ===

  getAPIRewrites() {
    return { beforeFiles: [], afterFiles: [], fallback: [] };
  }

  formatAPIResponse(data) {
    return data;
  }

  createManifestContent(data) {
    return { files: data.files, generatedAt: new Date().toISOString() };
  }
}

export function createNextBlogContentHandler(options = {}) {
  return new NextBlogContentHandler(options);
}
