/**
 * @fileoverview TemplateEngine - Unified Template System
 * @description Provides reusable template generation utilities for all virtual modules and discovery engines. Eliminates duplicate template patterns across plugins.
 *
 * @version 0.0.1
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */

export class TemplateEngine {
  /**
   * Generate virtual module content using templates
   * @param {Object} data - Discovery data
   * @param {Object} templates - Template configuration
   * @param {boolean} debug - Enable debug mode
   * @param {Object} [discoveryOptions] - Discovery options (for generateEmpty)
   * @param {string} [configKey] - Config key for _DNDEV_CONFIG_ (e.g., 'routes', 'themes')
   * @returns {string} Generated virtual module content
   */
  static generateVirtualModule(
    data,
    templates,
    debug = false,
    discoveryOptions = undefined,
    configKey = undefined
  ) {
    if (templates.isEmpty(data)) {
      return templates.generateEmpty(data, debug, discoveryOptions, configKey);
    }
    return templates.generateModule(data, debug, configKey);
  }

  /**
   * Generate inspection file content
   * @param {Object} data - Discovery data
   * @param {Object} templates - Template configuration
   * @param {string} configRoot - Configuration root path
   * @param {Object} discoveryOptions - Discovery options for templates that need them
   * @returns {string} Generated inspection content
   */
  static generateInspection(data, templates, configRoot, discoveryOptions) {
    // Check if the template function expects discoveryOptions (3+ parameters)
    if (templates.generateInspection.length >= 3) {
      return templates.generateInspection(data, configRoot, discoveryOptions);
    }
    // Fallback for templates that only expect 2 parameters
    return templates.generateInspection(data, configRoot);
  }

  /**
   * Wrap virtual module content with standard header
   * @param {string} moduleId - Virtual module identifier
   * @param {string} content - Module content
   * @returns {string} Wrapped module content
   */
  static wrapVirtualModule(moduleId, content) {
    return `// Virtual module: ${moduleId}
  // Generated by @donotdev/config discovery
  // Version: 1.0.0
  
  ${content}`;
  }

  /**
   * Generate globals population code for browser runtime
   * @param {string} globalName - Global variable name
   * @param {*} data - Data to populate
   * @param {string} debugMessage - Optional debug message
   * @returns {string} Generated globals code
   */
  static generateGlobals(globalName, data, debugMessage = '') {
    const dataString =
      typeof data === 'string' ? data : JSON.stringify(data, null, 2);

    return `
  if (typeof window !== 'undefined') {
    window.${globalName} = ${dataString};
    ${debugMessage ? `console.log('${debugMessage}');` : ''}
  }`;
  }

  /**
   * Generate inspection file header with metadata
   * @param {string} pluginName - Plugin name
   * @param {string} source - Source information
   * @param {string} usage - Usage information
   * @returns {string} Generated header
   */
  static generateInspectionHeader(pluginName, source = '', usage = '') {
    return `// Auto-generated ${pluginName} inspection file
  // Generated by @donotdev/config ${pluginName} discovery at ${new Date().toISOString()}
  // Version: 1.0.0${source ? `\n// Source: ${source}` : ''}${usage ? `\n// Runtime usage: ${usage}` : ''}
  
  `;
  }

  /**
   * Generate export statements from object
   * @param {Object} exports - Exports object
   * @returns {string} Generated export statements
   */
  static generateExports(exports) {
    return Object.entries(exports)
      .map(([name, value]) => {
        if (typeof value === 'function') {
          return `export ${value.toString().replace('function ', `function ${name} `)};`;
        }
        return `export const ${name} = ${JSON.stringify(value, null, 2)};`;
      })
      .join('\n\n');
  }

  /**
   * Generate default export statement
   * @param {*} exportObject - Object to export as default
   * @returns {string} Generated default export
   */
  static generateDefaultExport(exportObject) {
    return `export default ${JSON.stringify(exportObject, null, 2)};`;
  }

  /**
   * Generate production manifest from data
   * @param {Object} data - Discovery data
   * @param {Function} manifestGenerator - Custom manifest generator
   * @returns {Object} Generated manifest
   */
  static generateManifest(data, manifestGenerator) {
    const baseManifest = {
      generatedAt: new Date().toISOString(),
      version: '1.0.0',
      timestamp: Date.now(),
    };

    if (manifestGenerator && typeof manifestGenerator === 'function') {
      return {
        ...baseManifest,
        ...manifestGenerator(data),
      };
    }

    return baseManifest;
  }

  /**
   * Generate CSS module exports for use in JavaScript
   * @param {Map} utilitiesMap - Map of utility classes
   * @returns {string} Generated CSS module
   */
  static generateCSSModule(utilitiesMap) {
    if (utilitiesMap.size === 0) {
      return `// No utilities generated
  export const utilities = {};
  export default utilities;`;
    }

    const utilitiesObject = Object.fromEntries(utilitiesMap);

    return `// Auto-generated utility classes from discovered CSS variables
  // Generated by @donotdev/config at ${new Date().toISOString()}
  // Version: 1.0.0
  
  export const utilities = ${JSON.stringify(utilitiesObject, null, 2)};
  
  export const utilityNames = ${JSON.stringify(Array.from(utilitiesMap.keys()), null, 2)};
  
  export const stats = {
    totalUtilities: ${utilitiesMap.size},
    generatedAt: '${new Date().toISOString()}'
  };
  
  export default utilities;`;
  }

  /**
   * Generate helper functions template
   * @param {string} moduleId - Module identifier
   * @param {Object} helpers - Helper function definitions
   * @returns {string} Generated helper functions
   */
  static generateHelperFunctions(moduleId, helpers) {
    const helperCode = Object.entries(helpers)
      .map(([name, func]) => {
        if (typeof func === 'function') {
          return func.toString().replace('function ', `function ${name} `);
        }
        return `function ${name}() { ${func} }`;
      })
      .join('\n\n');

    return `// Helper functions for ${moduleId}
  // Generated by @donotdev/config
  
  ${helperCode}`;
  }

  /**
   * Validate template configuration
   * @param {Object} templates - Template configuration to validate
   * @returns {boolean} True if valid
   */
  static validateTemplates(templates) {
    const requiredMethods = [
      'isEmpty',
      'generateModule',
      'generateEmpty',
      'generateInspection',
    ];

    return requiredMethods.every(
      (method) => templates[method] && typeof templates[method] === 'function'
    );
  }

  /**
   * Create template configuration from discovery data
   * @param {string} pluginName - Plugin name
   * @param {Object} config - Template configuration
   * @returns {Object} Template configuration object
   */
  static createTemplateConfig(pluginName, config) {
    const {
      isEmpty = () => false,
      generateModule = () => '',
      generateEmpty = () => '',
      generateInspection = () => '',
      generateManifest = () => ({}),
      logConfig = () => {},
      logStats = () => {},
      logManifest = () => {},
    } = config;

    return {
      isEmpty,
      generateModule,
      generateEmpty,
      generateInspection,
      generateManifest,
      logConfig,
      logStats,
      logManifest,

      // Add metadata
      pluginName,
      version: '1.0.0',
      createdAt: new Date().toISOString(),
    };
  }

  /**
   * Get empty result data structure from discovery class with error info
   * DRY utility for error handling - ensures consistent structure across all plugins
   * @param {Object} discovery - Discovery class instance
   * @param {Error|string} error - Error message or Error instance
   * @returns {Object} Empty result data object with error info
   */
  static getEmptyResultWithError(discovery, error) {
    const errorMessage = error?.message || error || 'Unknown error';

    // Try to get empty result from discovery class
    if (discovery && typeof discovery._getEmptyResult === 'function') {
      try {
        const emptyResult = discovery._getEmptyResult();
        // Add error info to empty result
        if (emptyResult.errors && Array.isArray(emptyResult.errors)) {
          emptyResult.errors.push(errorMessage);
        } else if (emptyResult.errors === undefined) {
          emptyResult.errors = [errorMessage];
        }
        if (emptyResult.source === 'empty') {
          emptyResult.source = 'error';
        }
        return emptyResult;
      } catch (emptyResultError) {
        // Fallback if _getEmptyResult() fails
        return {
          errors: [errorMessage],
          source: 'error',
        };
      }
    }

    // Discovery class doesn't have _getEmptyResult() (e.g., EnvDiscovery)
    return {
      errors: [errorMessage],
      source: 'error',
    };
  }
}
