/**
 * @fileoverview Vite Theme Plugin - Factory Implementation
 * @description Minimal plugin definition using the discovery factory for theme and CSS variable discovery.
 *
 * @version 0.0.2
 * @since 0.0.1
 * @author AMBROISE PARK Consulting
 */

import { createDiscoveryPlugin } from './PluginFactory.js';
import {
  VIRTUAL_MODULES,
  GENERATED_PATHS,
  CONFIG_KEYS,
} from '../../constants.js';
import { ThemeDiscovery } from '../../discovery/ThemeDiscovery.js';
import { createMissingResourceError } from '../../utils/buildError.js';
import { CSSExtractor } from '../../utils/CSSExtractor.js';
import { createLogger } from '../../utils/debugLog.js';

// Theme-specific templates
const themeTemplates = {
  /**
   * Check if theme data is empty
   */
  isEmpty: (themeData) => !themeData.themes || themeData.themes.length === 0,

  /**
   * Generate main virtual module
   */
  generateModule: (themeData, debug, configKey = 'themes') => {
    const { themes } = themeData;

    // If no themes discovered, use essential themes fallback (shouldn't happen due to _addEssentialThemes, but safety net)
    if (!themes || themes.length === 0) {
      // Fall through to generateEmpty which will use essential themes
      return themeTemplates.generateEmpty(
        themeData,
        debug,
        undefined,
        configKey
      );
    }

    const defaultTheme =
      themes.find((t) => t.essential && t.name === 'light') || themes[0];
    const manifest = {
      totalThemes: themes.length,
      defaultTheme: defaultTheme?.name || 'light',
      hasCustomThemes: themes.some((t) => !t.essential),
      timestamp: new Date().toISOString(),
    };

    return `// Virtual module: ${VIRTUAL_MODULES.themes}
// 🚀 STATIC INJECTION PATTERN - Zero Runtime Loading
// Generated by @donotdev/config at ${new Date().toISOString()}

// ===== STATIC EXPORTS - IMMEDIATE AVAILABILITY =====
export const THEMES = ${JSON.stringify(themes, null, 2)};
export const THEME_MANIFEST = ${JSON.stringify(manifest, null, 2)};
export const THEME_COUNT = ${themes.length};
export const DEFAULT_THEME = '${defaultTheme?.name || 'light'}';

const themeData = THEMES;
const defaultTheme = DEFAULT_THEME;
const themeManifest = THEME_MANIFEST;

// Populate unified DnDev config for runtime access
if (typeof globalThis !== 'undefined') {
  // Initialize _DNDEV_CONFIG_ if it doesn't exist
  if (!globalThis._DNDEV_CONFIG_) {
    globalThis._DNDEV_CONFIG_ = {
      platform: 'vite',
      mode: 'development',
      version: '1.0.0',
      context: 'client',
      timestamp: Date.now(),
    };
  }
  
  // Populate themes configuration
  globalThis._DNDEV_CONFIG_.${CONFIG_KEYS[configKey]} = {
    discovered: themeData,
    mapping: themeData.reduce((acc, theme) => {
      acc[theme.name] = theme;
      return acc;
    }, {}),
    variables: {},
    manifest: {
      totalThemes: ${themes.length},
      totalVariables: 0,
      generatedAt: new Date().toISOString(),
    },
  };
}

// Theme helper functions
export function getTheme(themeName) {
  return themeData.find(t => t.name === themeName) || null;
}

export function getDefaultTheme() {
  return themeData.find(t => t.name === defaultTheme) || null;
}

export function getAllThemes() {
  return themeData;
}

export function getThemeNames() {
  return themeData.map(t => t.name);
}

// Named exports for convenience
export const themes = themeData;
export const manifest = themeManifest;
export const defaultName = defaultTheme;

// Default export
export default { 
  themes, 
  manifest, 
  defaultName, 
  getTheme, 
  getDefaultTheme, 
  getAllThemes, 
  getThemeNames 
};
`;
  },

  /**
   * Generate empty virtual module - Uses framework essential themes as fallback
   */
  generateEmpty: (data, debug, discoveryOptions, configKey = 'themes') => {
    // Use essential themes from discovery data, or fallback to light theme
    const themes =
      data.themes && data.themes.length > 0
        ? data.themes
        : [
            {
              name: 'light',
              displayName: 'Light',
              meta: { icon: 'Sun', category: 'light' },
              essential: true,
              isDark: false,
              source: 'built-in',
              variableCount: 0,
            },
          ];

    const defaultTheme =
      themes.find((t) => t.essential && t.name === 'light') || themes[0];
    const manifest = {
      totalThemes: themes.length,
      defaultTheme: defaultTheme?.name || 'light',
      hasCustomThemes: themes.some((t) => !t.essential),
      timestamp: new Date().toISOString(),
    };

    return `// ${VIRTUAL_MODULES.themes} - Using framework essential themes (fallback)
// Generated by @donotdev/config at ${new Date().toISOString()}

export const THEMES = ${JSON.stringify(themes, null, 2)};
export const THEME_MANIFEST = ${JSON.stringify(manifest, null, 2)};
export const THEME_COUNT = ${themes.length};
export const DEFAULT_THEME = '${defaultTheme?.name || 'light'}';

const themeData = THEMES;
const defaultTheme = DEFAULT_THEME;
const themeManifest = THEME_MANIFEST;

// Populate unified DnDev config for runtime access
if (typeof globalThis !== 'undefined') {
  if (!globalThis._DNDEV_CONFIG_) {
    globalThis._DNDEV_CONFIG_ = {
      platform: 'vite',
      mode: 'development',
      version: '1.0.0',
      context: 'client',
      timestamp: Date.now(),
    };
  }
  
  globalThis._DNDEV_CONFIG_.${CONFIG_KEYS[configKey]} = {
    discovered: themeData,
    mapping: themeData.reduce((acc, theme) => {
      acc[theme.name] = theme;
      return acc;
    }, {}),
    variables: {},
    manifest: {
      totalThemes: ${themes.length},
      generatedAt: new Date().toISOString(),
    },
  };
}

export function getTheme(themeName) {
  return themeData.find(t => t.name === themeName) || null;
}

export function getDefaultTheme() {
  return themeData.find(t => t.name === defaultTheme) || null;
}

export function getAllThemes() {
  return themeData;
}

export function getThemeNames() {
  return themeData.map(t => t.name);
}

export const themes = themeData;
export const manifest = themeManifest;
export const defaultName = defaultTheme;

export default { 
  themes, 
  manifest, 
  defaultName, 
  getTheme, 
  getDefaultTheme, 
  getAllThemes, 
  getThemeNames 
};
`;
  },

  /**
   * Generate inspection file content
   */
  generateInspection: (themeData, configRoot) => {
    const { themes } = themeData;

    if (!themes || themes.length === 0) {
      return `/**
 * Generated Theme Discovery Results
 * Source: empty
 * Generated at: ${new Date().toISOString()}
 */

export const discoveredThemes = [];
export const defaultTheme = 'light';
export const themeFiles = [];

export const themeManifest = {
  totalThemes: 0,
  generatedAt: '${new Date().toISOString()}'
};

export default discoveredThemes;
`;
    }

    const defaultTheme =
      themes.find((t) => t.essential && t.name === 'light') || themes[0];

    return `/**
 * Generated Theme Discovery Results
 * Generated at: ${new Date().toISOString()}
 * Import from '${VIRTUAL_MODULES.themes}'
 */

export const discoveredThemes = ${JSON.stringify(themes, null, 2)};

export const defaultTheme = '${defaultTheme?.name || 'light'}';

export const themeFiles = ${JSON.stringify(
      themeData.files?.map((f) => ({
        name: f.name,
        path: f.relativePath,
        size: f.size,
      })) || [],
      null,
      2
    )};

export const themeManifest = {
  totalThemes: ${themes.length},
  generatedAt: '${new Date().toISOString()}'
};

export default discoveredThemes;
`;
  },

  /**
   * Generate production manifest
   */
  generateManifest: (themeData) => ({
    themes: themeData.themes?.length || 0,
    timestamp: Date.now(),
    hasCustomThemes: themeData.themes?.some((t) => !t.essential) || false,
  }),

  /**
   * Log configuration details
   */
  logConfig: (options) => {
    // Using debug logger - will be replaced by plugin factory
  },

  /**
   * Log discovery stats - show WHAT was found, not timing
   */
  logStats: (themeData, icon, logger) => {
    const themes = themeData.themes || [];
    const customThemes = themes.filter((t) => !t.essential).length;
    const totalThemes = themes.length;

    if (logger) {
      // Framework always has essential themes, so this should never be 0
      // But if it is, log a warning instead of throwing (essential themes should be present)
      if (totalThemes === 0) {
        logger.warn(
          `${icon} No themes discovered - using framework essential themes fallback`
        );
      } else {
        logger.info(
          `${icon} Themes: ${totalThemes} discovered${customThemes > 0 ? ` (${customThemes} custom)` : ''}`
        );
      }
    }
  },
};

// File patterns for HMR
const themeFilePatterns = [
  (file) => file.endsWith('.css'),
  (file) => file.includes('theme'),
  (file) => file.includes('styles'),
];

// Create the plugin using createDiscoveryPlugin
export function createViteThemePlugin(options = {}) {
  const startTime = Date.now();
  const logger = createLogger('theme-plugin', options.debug, options.verbose);

  logger.debug('🎨 Creating theme discovery plugin...');

  const plugin = createDiscoveryPlugin({
    pluginName: 'dndev-theme',
    icon: '🎨',
    virtualModuleId: VIRTUAL_MODULES.themes,
    DiscoveryClass: ThemeDiscovery,
    discoveryMethod: 'discoverThemes',
    filePatterns: ['**/*.css'],
    templates: themeTemplates,
    manifestFileName: GENERATED_PATHS.manifests.theme,
    configKey: 'themes',
    createDiscovery: (pathResolver, discoveryOptions) => {
      const cssExtractor = new CSSExtractor(pathResolver, {
        debug: discoveryOptions.debug,
        logger: createLogger(
          'css-extractor',
          discoveryOptions.debug,
          discoveryOptions.verbose
        ),
      });
      return new ThemeDiscovery(cssExtractor, pathResolver, discoveryOptions);
    },
  })(options);

  // Plugin created - no spam needed
  return plugin;
}
